# Generated by Django 4.0.6 on 2022-07-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centersmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='centersmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='centersmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='centersmodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='centersmodel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='centersmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='centersmodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='centersmodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='centersmodel',
            name='url',
        ),
        migrations.RemoveField(
            model_name='centersmodel',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='centersmodel',
            name='interface_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centersmodel',
            name='ipv6_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centersmodel',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centersmodel',
            name='prefix_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='centersmodel',
            name='vlan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
